### ISSUE TITLE
emoticonsCompat is deleting unecessary characters and breaking the typed emoticon

### ISSUE THREAD

**Issue by brunoais** [samclarke/SCEditor#451]
E.g. 
With the default emoticons, 
If you type

	. :) q

You get:

	. ::)

and the emoticon is not translated into the image.
Confirmed in firefox 38.

https://github.com/mybb/mybb/issues/2045

**Comment by samclarke** [comment]
I've just tested this and it seems to be fixed for me by 90a4d59cc8a6a33dc969a7602c965c2f5af490d2. Could you check if it's fixed in the master branch for you?

If that has fixed it then we will have to create a new release as that's quite a bad bug.

**Comment by Destroy666x** [comment]
IndexSizeError is also fixed by that commit, right?

**Comment by brunoais** [comment]
@samclarke 
Is that on the master branch?
I updated my version to the master, I went to the manual tests and it didn't seem solved. That's how I reproduced it...

**Comment by samclarke** [comment]
@brunoais Yes it's the master branch. I've tried a few more different ways to reproduce this and that commit fixes all I've tried in both Chrome and Firefox.

I'm still not sure if it has actually fixed it or just fixed the way I'm reproducing it. Could you see if it's [fixed here](https://dl.dropboxusercontent.com/u/56830471/1.4.8/example.html)?

@Destroy666x Yes, at least for me it does.

**Comment by Destroy666x** [comment]
Both issues seem to be solved for me in that demo, yes.

**Comment by samclarke** [comment]
I've just managed to reproduce it with that commit although it does seem to have partially fixed it.

**Comment by samclarke** [comment]
I've fixed what I think was causing the issue. The other commit was just reducing the number of ways to trigger the bug and didn't actually fix it.

Could you see if you can still reproduce it [here](https://dl.dropboxusercontent.com/u/56830471/emoticonsCompat/example.html)?

**Comment by brunoais** [comment]
I can't reproduce the way I was being able to. Sounds like it is solved to me.
@Destroy666x please test it too.

**Comment by Destroy666x** [comment]
I can't reproduce either.

**Comment by MangaD** [comment]
Great job, it is fixed indeed!
Small detail - smilies at the start of a line are not translated into the image after they are typed.
Not too important, but still what I would call a bug.

**Comment by brunoais** [comment]
Seems solved and forgotten.
Closed
